version: '3.7'

services:
  app:
    hostname: "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    image: "${DRUPAL_IMAGE}"
    volumes:
      - .:/app:delegated
    depends_on:
      - db
    environment:
      APP_ENV: "${APP_ENV:-local}"
      DRUPAL_ROUTES: "https://varnish-${DRUPAL_HOSTNAME},https://helfi-proxy.docker.so,http://${COMPOSE_PROJECT_NAME}-varnish"
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}"
      # To enable xdebug, run `export XDEBUG_ENABLE=true` before (re)starting your project.
      # Optionally, you can add this to your default environments variables to enable or disable
      # xdebug by default (like /etc/environments, ~/.bashrc, or ~/.zshrc).
      XDEBUG_ENABLE: "${XDEBUG_ENABLE:-false}"
      # DOCKERHOST: host.docker.internal
      # Use drush server to run functional tests so we don't have to care about
      # permission issues.
      SIMPLETEST_BASE_URL: "http://127.0.0.1:8888"
      SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
      BROWSERTEST_OUTPUT_BASE_URL: "https://${DRUPAL_HOSTNAME}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${DRUPAL_HOSTNAME}:host-gateway"
    networks:
      - internal
      - stonehenge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"
  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: mariadb:10.9
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306
    networks:
      - internal
networks:
  internal:
    external: false
  stonehenge-network:
    external: true

volumes:
  db_data:
  ssh:
    name: stonehenge-ssh
    external: true
